apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: nordmart-dev-tools
---
# Role & Role binding for namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-binding
  namespace: nordmart-dev-tools
subjects:
- kind: ServiceAccount
  name: flux
roleRef:
  kind: Role
  name: flux-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-role
  namespace: nordmart-dev-tools
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
#Global
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-system-role
  namespace: kube-system
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-system-binding-nordmart-dev
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: flux
  namespace: nordmart-dev-tools
roleRef:
  kind: Role
  name: flux-system-role
  apiGroup: rbac.authorization.k8s.io
---
#Monitoring
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-monitoring-role
  namespace: monitoring
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-binding-nordmart-dev
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: flux
  namespace: nordmart-dev-tools
roleRef:
  kind: Role
  name: flux-monitoring-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-role
  namespace: istio-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: nordmart-dev-tools
roleRef:
  kind: Role
  name: flux-nordmart-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-role
  namespace: istio-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: nordmart-dev-tools
roleRef:
  kind: Role
  name: flux-nordmart-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-role
  namespace: nordmart-dev-apps
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-nordmart-binding
  namespace: nordmart-dev-apps
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: nordmart-dev-tools
roleRef:
  kind: Role
  name: flux-nordmart-role
  apiGroup: rbac.authorization.k8s.io