apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-strimzi-kafka-operator
  namespace: nordmart-demo-tools
spec:
  releaseName: nordmart-dev-strimzi-kafka-operator
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.16.0
  values:
    watchNamespaces:
      - nordmart-demo
    watchAnyNamespace: false
